import 'server-only';
import mongoose, { Schema, type InferSchemaType, type Model, Types } from 'mongoose';

const { Mixed, ObjectId } = Schema.Types;
const ts = { timestamps: true } as const;

function model<T>(name: string, schema: Schema<T>): Model<T> {
  return (mongoose.models[name] as Model<T>) ?? mongoose.model<T>(name, schema);
}

/* Tenancy & access */

const OrganizationSchema = new Schema(
  {
    name: { type: String, required: true },
    /** The license currently in force (see src/server/license.ts). */
    licenseId: { type: ObjectId },
  },
  ts,
);

export const ROLES = ['owner', 'admin', 'preparer', 'reviewer', 'viewer'] as const;
export type Role = (typeof ROLES)[number];

const UserSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true, index: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    name: { type: String, required: true },
    passwordHash: { type: String, required: true, select: false },
    role: { type: String, enum: ROLES, required: true },
    /** Empty = all companies in the org. */
    companyIds: [{ type: ObjectId }],
    active: { type: Boolean, default: true },
  },
  ts,
);

const CompanySchema = new Schema(
  {
    orgId: { type: ObjectId, required: true, index: true },
    name: { type: String, required: true },
    gstin: { type: String, required: true, uppercase: true },
    stateCode: { type: String, required: true },
    aatoAbove5Cr: { type: Boolean, default: false },
    filingFrequency: { type: String, enum: ['monthly', 'quarterly'], default: 'monthly' },
    /** GSTN's public taxpayer record, when the company was added from its GSTIN. */
    legalName: String,
    tradeName: String,
    registrationStatus: String,
    constitution: String,
    taxpayerType: String,
    registrationDate: String,
    address: String,
    profileFetchedAt: Date,
  },
  ts,
);
CompanySchema.index({ orgId: 1, gstin: 1 }, { unique: true });

/* Returns */

import { RETURN_STATUSES } from './gst/gst-status/statuses';
export { RETURN_STATUSES };

const GstReturnSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    fp: { type: String, required: true }, // MMYYYY
    fy: { type: String, required: true },
    quarterly: { type: Boolean, default: false },
    status: { type: String, enum: RETURN_STATUSES, default: 'draft' },
    statusHistory: [
      {
        _id: false, from: String, to: String, at: Date, by: ObjectId, byEmail: String, note: String, evidenceId: ObjectId,
      },
    ],
    /** References copied from portal evidence the user supplied – never generated by the app. */
    portal: {
      uploadReference: String,
      processingReference: String,
      arn: String,
      filedOn: Date,
      /** API integration only – values returned by GSTN through the client named in filedVia. */
      proceedReference: String,
      proceededAt: Date,
      summaryEvidenceId: ObjectId,
      evcRequestedAt: Date,
      fileSubmittedAt: Date,
      ackNum: String,
      filedVia: String,
    },
    profileId: String,
    importInfo: {
      fileName: String,
      importedAt: Date,
      sheetsParsed: Mixed,
      sheetsSkipped: Mixed,
      importIssueCount: Number,
    },
    /** One entry per marketplace (amazon, flipkart, meesho, generic): files and reconciliation summary of its last import. */
    marketplaceImports: [{ _id: false, marketplace: String, label: String, importedAt: Date, etin: String, uqc: String, summary: Mixed }],
    summary: Mixed,
    lastValidatedAt: Date,
    currentJsonId: { type: ObjectId },
    jsonStale: { type: Boolean, default: false },
  },
  ts,
);
GstReturnSchema.index({ orgId: 1, companyId: 1, fp: 1 }, { unique: true });

const Gstr1RecordSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true },
    section: { type: String, required: true },
    key: { type: String, required: true },
    source: Mixed,
    data: { type: Mixed, required: true },
    hasErrors: { type: Boolean, default: false },
    hasWarnings: { type: Boolean, default: false },
    edited: { type: Boolean, default: false },
  },
  { ...ts, minimize: false },
);
Gstr1RecordSchema.index({ returnId: 1, section: 1, hasErrors: -1 });

const Gstr1ErrorSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true },
    origin: { type: String, enum: ['import', 'validation', 'portal'], required: true },
    recordKey: String,
    code: String,
    severity: { type: String, enum: ['error', 'warning'] },
    section: String,
    documentNo: String,
    sheet: String,
    row: Number,
    field: String,
    value: Mixed,
    message: String,
    suggestion: String,
  },
  ts,
);
Gstr1ErrorSchema.index({ returnId: 1, origin: 1, severity: 1 });

const GeneratedJsonSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true, index: true },
    version: String,
    profileId: String,
    /** Stored as the exact string that is downloaded/uploaded so the hash stays verifiable. */
    payload: { type: String, required: true },
    sha256: { type: String, required: true },
    sizeBytes: Number,
    log: Mixed,
    createdBy: ObjectId,
  },
  ts,
);

/* GST portal step (manual today; official integration later) */

const UploadJobSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true, index: true },
    jsonId: { type: ObjectId, required: true },
    jsonSha256: String,
    /** Which GstClient handled it – "manual" means the user uploads on the GST portal. */
    client: { type: String, required: true },
    status: { type: String, enum: ['uploading', 'uploaded', 'processing', 'processed', 'error', 'cancelled', 'filed'], default: 'uploading' },
    reference: String,
    portalErrorCount: Number,
    history: [{ _id: false, at: Date, status: String, note: String, by: String }],
    createdBy: ObjectId,
  },
  ts,
);

export const EVIDENCE_KINDS = ['upload_reference', 'error_report', 'processing_result', 'summary', 'acknowledgement', 'note', 'offset'] as const;

/** Anything the user brings back from the GST portal: references, reports, acknowledgements. */
const PortalEvidenceSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true, index: true },
    uploadJobId: ObjectId,
    kind: { type: String, enum: EVIDENCE_KINDS, required: true },
    reference: String,
    note: String,
    fileName: String,
    contentType: String,
    sizeBytes: Number,
    sha256: String,
    content: { type: Buffer, select: false },
    recordedBy: ObjectId,
    recordedByEmail: String,
  },
  ts,
);

/**
 * Taxpayer session with GSTN through an API integration (one per company). The access token and the
 * GST username are AES-256-GCM encrypted, bound to org/company/GSTIN, and never leave the server.
 */
const GstApiSessionSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    client: { type: String, required: true },
    state: { type: String, enum: ['otp_sent', 'active', 'expired', 'none'], default: 'none' },
    usernameEnc: { type: String, select: false },
    tokenEnc: { type: String, select: false },
    otpSentAt: Date,
    sessionExpiresAt: Date,
    tokenExpiresAt: Date,
    lastRefreshAt: Date,
    startedBy: ObjectId,
    startedByEmail: String,
  },
  ts,
);
GstApiSessionSchema.index({ orgId: 1, companyId: 1 }, { unique: true });

/** GST portal (browser-protocol) session per company. The cookie jar is encrypted and never leaves the server. */
const GstSessionSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    state: { type: String, enum: ['captcha_required', 'otp_required', 'active', 'failed', 'expired', 'none'], default: 'none' },
    jarEnc: { type: String, select: false },
    expiresAt: Date,
    lastActivityAt: Date,
    message: String,
    startedBy: ObjectId,
  },
  ts,
);
GstSessionSchema.index({ orgId: 1, companyId: 1 }, { unique: true });

/** Saved (encrypted) GST portal username per company, when the user opts to remember it. */
const GstProfileSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    usernameEnc: String,
  },
  ts,
);
GstProfileSchema.index({ orgId: 1, companyId: 1 }, { unique: true });

/* GSTR-3B (one per company + period; filed through the GST API integration) */

export const GSTR3B_STATUSES = ['draft', 'saving', 'saved', 'offset', 'filed'] as const;

/**
 * GSTR-3B: draft tables prepared in the app, what GSTN holds (saved values, auto-calculated liability,
 * ledger balance) and each portal step. GSTN responses are kept as PortalEvidence with returnId = this _id.
 */
const Gstr3bSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    fp: { type: String, required: true }, // MMYYYY
    status: { type: String, enum: GSTR3B_STATUSES, default: 'draft' },
    /** Tables 3.1 – 5.1 as prepared here (GSTN's JSON shape). */
    form: Mixed,
    formSource: { type: String, enum: ['auto', 'portal', 'manual', 'excel'] },
    formUpdatedAt: Date,
    formUpdatedBy: String,
    /** GSTN snapshots from the last fetch. */
    autoLiability: Mixed,
    autoFetchedAt: Date,
    portalForm: Mixed,
    portalDetails: Mixed,
    portalFetchedAt: Date,
    ledger: Mixed,
    ledgerFetchedAt: Date,
    fetchNotes: [String],
    portal: {
      saveReference: String,
      savedAt: Date,
      saveErrors: [String],
      detailsEvidenceId: ObjectId,
      offsetEvidenceId: ObjectId,
      offsetAt: Date,
      evcRequestedAt: Date,
      fileSubmittedAt: Date,
      ackNum: String,
      nil: Boolean,
      arn: String,
      filedOn: Date,
      filedVia: String,
    },
    history: [{ _id: false, at: Date, from: String, to: String, note: String, byEmail: String }],
  },
  { ...ts, minimize: false },
);
Gstr3bSchema.index({ orgId: 1, companyId: 1, fp: 1 }, { unique: true });

/* Annual returns: GSTR-9 and GSTR-9C (one per company + financial year; prepared offline) */

export const ANNUAL_KINDS = ['gstr9', 'gstr9c'] as const;
export const ANNUAL_STATUSES = ['draft', 'filed'] as const;

/**
 * GSTR-9 / GSTR-9C prepared in the app (manual entry, Excel or JSON import, or auto-filled from the
 * year's GSTR-1 / GSTR-3B / GSTR-9) and downloaded for the GST portal. Filing happens on the portal;
 * the ARN is recorded here by the user.
 */
const AnnualReturnSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    kind: { type: String, enum: ANNUAL_KINDS, required: true },
    fy: { type: String, required: true }, // "2024-25"
    status: { type: String, enum: ANNUAL_STATUSES, default: 'draft' },
    /** { v, lists, text } – see src/server/gst/annual/common.ts. */
    form: Mixed,
    formSource: { type: String, enum: ['auto', 'manual', 'excel', 'json', 'portal'] },
    formUpdatedAt: Date,
    formUpdatedBy: String,
    /** What the last auto-fill or import could not do – shown until the next one. */
    notes: [String],
    filed: { arn: String, filedOn: Date, recordedAt: Date, recordedBy: String },
    history: [{ _id: false, at: Date, from: String, to: String, note: String, byEmail: String }],
  },
  { ...ts, minimize: false },
);
AnnualReturnSchema.index({ orgId: 1, companyId: 1, kind: 1, fy: 1 }, { unique: true });

/* Purchases & ITC reconciliation (books ↔ GSTR-2A / GSTR-2B) */

export const PURCHASE_SOURCES = ['books', 'gstr2a', 'gstr2b'] as const;

/** One purchase document (invoice / credit note / debit note) from the books or the portal, per company and period. */
const PurchaseDocSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    /** Period the data was uploaded for (MMYYYY). */
    fp: { type: String, required: true },
    source: { type: String, enum: PURCHASE_SOURCES, required: true },
    key: { type: String, required: true },
    docType: { type: String, enum: ['INV', 'CN', 'DN'], required: true },
    supplierGstin: { type: String, required: true },
    supplierName: String,
    docNo: { type: String, required: true },
    docDate: String,
    pos: String,
    rcm: Boolean,
    taxable: Number, igst: Number, cgst: Number, sgst: Number, cess: Number,
    invoiceValue: Number,
    itcAvailable: Boolean,
    itcReason: String,
    /** Period the document belongs to in the source data (2B/2A return period, or the books period). */
    period: String,
    supplierPeriod: String,
    supplierFilingDate: String,
    supplierFiled: Boolean,
    gstinCancelledOn: String,
    amended: Boolean,
    originalDocNo: String,
    origin: { _id: false, file: String, row: Number, sheet: String },
    importId: ObjectId,
  },
  { ...ts, minimize: false },
);
PurchaseDocSchema.index({ orgId: 1, companyId: 1, source: 1, fp: 1 });

/** An upload (or portal download) of one source for one company + period. */
const PurchaseImportSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    fp: { type: String, required: true },
    source: { type: String, enum: PURCHASE_SOURCES, required: true },
    via: { type: String, enum: ['file', 'portal'], default: 'file' },
    files: [String],
    docs: Number,
    taxable: Number,
    tax: Number,
    notes: Mixed,
    importedBy: String,
  },
  ts,
);
PurchaseImportSchema.index({ orgId: 1, companyId: 1, fp: 1, source: 1 }, { unique: true });

/** A user decision in a reconciliation (ignore a document, link two documents, accept differences). */
const ReconDecisionSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    fp: { type: String, required: true },
    /** Which reconciliation: books vs GSTR-2A or vs GSTR-2B. */
    against: { type: String, enum: ['gstr2a', 'gstr2b'], required: true },
    action: { type: String, enum: ['ignore', 'link', 'accept'], required: true },
    booksKey: String,
    portalKey: String,
    reason: String,
    by: ObjectId,
    byEmail: String,
  },
  ts,
);
ReconDecisionSchema.index({ orgId: 1, companyId: 1, fp: 1, against: 1 });

/* Returns downloaded from the GST portal (download centre) */

/**
 * One return, ledger or filing list fetched from GSTN for a company and period. GSTN's JSON is kept in
 * GridFS (bucket "clientfiles"), so it can be downloaded again – as JSON or Excel – without another
 * API call.
 */
const PortalFetchSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    /** gstr1 | gstr3b | gstr2a | gstr2b | gstr9 | cash_ledger | itc_ledger | filed */
    type: { type: String, required: true },
    /** MMYYYY for monthly returns, "2025-26" for yearly ones. */
    period: { type: String, required: true },
    fileId: ObjectId,
    sizeBytes: Number,
    /** Rows/documents GSTN returned (0 = nothing for this period). */
    count: { type: Number, default: 0 },
    notes: [String],
    fetchedBy: String,
    /** Set when the data was also added to Client documents. */
    clientDocId: ObjectId,
    /** What happened to the app's own form (GSTR-1, GSTR-3B, GSTR-9) for this period. */
    form: { state: String, note: String, link: String },
  },
  ts,
);
PortalFetchSchema.index({ orgId: 1, companyId: 1, type: 1, period: 1 }, { unique: true });

/* Client documents (upload → understand → extract → check) */

export const DOC_STATUSES = ['queued', 'processing', 'processed', 'needs_review', 'failed', 'duplicate'] as const;

/**
 * An uploaded client document. The file itself is in GridFS (bucket "clientfiles"); what it is, whose
 * it is and which period it belongs to are detected, by rules for structured files or by AI.
 */
const ClientDocSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    /** Null until the client is identified (upload with "detect client"). */
    companyId: { type: ObjectId, default: null },
    fileId: { type: ObjectId, required: true },
    fileName: { type: String, required: true },
    contentType: String,
    sizeBytes: Number,
    sha256: { type: String, required: true },
    batchId: String,
    status: { type: String, enum: DOC_STATUSES, default: 'queued' },
    /** What the document is (see src/engine/docs/types.ts DOC_KINDS). */
    kind: String,
    kindReason: String,
    /** "rules" (structured file) or "ai". */
    method: String,
    confidence: Number,
    /** Main return period of the contents (MMYYYY) and its financial year. */
    fp: String,
    fy: String,
    gstins: [String],
    notes: [String],
    error: String,
    duplicateOf: ObjectId,
    /** Set by the CA when the detected type is wrong (e.g. a sales register taken as purchases). */
    kindOverride: String,
    /** What was read from the file (before client/period assignment) – reused on reprocessing so AI is not paid for twice. */
    extraction: { type: Mixed, select: false },
    counts: { records: Number, review: Number, errors: Number },
    ai: { model: String, inputTokens: Number, outputTokens: Number, costInr: Number },
    attempts: { type: Number, default: 0 },
    startedAt: Date,
    processedAt: Date,
    uploadedBy: String,
  },
  ts,
);
ClientDocSchema.index({ orgId: 1, companyId: 1, fy: 1, fp: 1 });
ClientDocSchema.index({ orgId: 1, status: 1 });
ClientDocSchema.index({ orgId: 1, sha256: 1 });

/** One invoice or bank transaction extracted from a ClientDoc. */
const DocRecordSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    docId: { type: ObjectId, required: true },
    kind: { type: String, enum: ['invoice', 'bank'], required: true },
    /** Invoices: document | register | gstr1 | gstr2a | gstr2b. */
    source: String,
    direction: { type: String, enum: ['sales', 'purchase', null], default: null },
    fp: String,
    fy: String,
    data: { type: Mixed, required: true },
    /** Data as first extracted, kept when the CA corrects it. */
    original: Mixed,
    loc: { page: Number, sheet: String, row: Number },
    uncertain: [String],
    flags: [{ _id: false, code: String, severity: String, field: String, message: String, relatedId: String }],
    review: { type: String, enum: ['ok', 'review', 'approved', 'rejected'], default: 'ok' },
    reviewedBy: String,
    reviewedAt: Date,
    /** Duplicate detection and search. */
    dupKey: String,
    nearKey: String,
    party: String,
    docNo: String,
    amount: Number,
    text: String,
  },
  { ...ts, minimize: false },
);
DocRecordSchema.index({ orgId: 1, companyId: 1, fp: 1, kind: 1 });
DocRecordSchema.index({ orgId: 1, docId: 1 });
DocRecordSchema.index({ orgId: 1, companyId: 1, dupKey: 1 });
DocRecordSchema.index({ orgId: 1, companyId: 1, nearKey: 1 });

/* AI assistant conversations (one client each) */

/**
 * A conversation with the assistant about one client's data. `messages` is the exact Messages API
 * history (thinking and tool blocks unchanged – the next turn must replay it as is); `turns` is what
 * the screen shows.
 */
const AssistantChatSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    userId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    title: String,
    /** Which AI service the stored messages are for ("claude" when missing); another one starts from the turns' text. */
    provider: String,
    messages: { type: [Mixed], select: false },
    turns: [{ _id: false, role: String, text: String, tools: Mixed, at: Date, error: Boolean }],
    usage: { inputTokens: { type: Number, default: 0 }, outputTokens: { type: Number, default: 0 }, cacheReadTokens: { type: Number, default: 0 } },
  },
  { ...ts, minimize: false },
);
AssistantChatSchema.index({ orgId: 1, userId: 1, companyId: 1, updatedAt: -1 });

/** One AI API call (Claude or Groq) made for an organisation – what it cost, for the monthly AI allowance. */
const AiUsageSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    /** "YYYY-MM" (calendar month, India time). */
    month: { type: String, required: true },
    kind: { type: String, enum: ['extract', 'assistant'], required: true },
    model: String,
    inputTokens: Number, outputTokens: Number, cacheReadTokens: Number, cacheWriteTokens: Number,
    costInr: { type: Number, required: true },
    refId: String,
    byEmail: String,
  },
  ts,
);
AiUsageSchema.index({ orgId: 1, month: 1 });

/* Platform: super admin, packages and licenses (not scoped to an org) */

/** Software owner. Separate from org users; signs in at /admin. */
const SuperAdminSchema = new Schema(
  {
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    name: { type: String, default: 'Super Admin' },
    passwordHash: { type: String, required: true, select: false },
    active: { type: Boolean, default: true },
    lastLoginAt: Date,
  },
  ts,
);

export const FEATURE_KEYS = ['validators', 'gstApi', 'marketplaceImport', 'manualEntry', 'reconciliation', 'documentAI'] as const;
export type FeatureKey = (typeof FEATURE_KEYS)[number];

/** A sellable plan. 0 in a limit means unlimited. */
const PackageSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    description: String,
    priceInr: { type: Number, default: 0 },
    durationDays: { type: Number, required: true },
    limits: {
      companies: { type: Number, default: 0 },
      users: { type: Number, default: 0 },
      returnsPerMonth: { type: Number, default: 0 },
    },
    features: [{ type: String, enum: FEATURE_KEYS }],
    /** Document AI: Claude API spend allowed per calendar month, in ₹ (0 = unlimited). */
    aiBudgetInr: { type: Number, default: 0 },
    /** Given automatically to new sign-ups. */
    isTrial: { type: Boolean, default: false },
    /** Archived packages keep working for existing licenses but cannot be issued. */
    active: { type: Boolean, default: true },
  },
  ts,
);

export const LICENSE_STATUSES = ['unused', 'active', 'suspended', 'revoked', 'replaced'] as const;

const LicenseSchema = new Schema(
  {
    key: { type: String, required: true, unique: true },
    packageId: { type: ObjectId, required: true, index: true },
    durationDays: { type: Number, required: true },
    status: { type: String, enum: LICENSE_STATUSES, default: 'unused' },
    orgId: { type: ObjectId, index: true },
    activatedAt: Date,
    expiresAt: Date,
    /** Customer name / reference, for the super admin's records. */
    issuedTo: String,
    note: String,
    createdBy: ObjectId,
    /** Add-ons bought on top of the package limits; they end with this license. */
    extras: {
      companies: { type: Number, default: 0 },
      users: { type: Number, default: 0 },
      returnsPerMonth: { type: Number, default: 0 },
    },
  },
  ts,
);

/** Platform-wide settings edited by the super admin (single document, key "platform"). */
const PlatformSettingsSchema = new Schema(
  {
    key: { type: String, required: true, unique: true, default: 'platform' },
    upiId: String,
    payeeName: String,
    /** Shown under the QR code, e.g. "Send the screenshot after paying; activation within 2 hours." */
    paymentNote: String,
    /** Add-on prices in ₹ (0 = not sold): per extra company, per extra team member, per block of 10 returns/month. */
    addonPrices: {
      companies: { type: Number, default: 0 },
      users: { type: Number, default: 0 },
      returnsPerMonth: { type: Number, default: 0 },
    },
  },
  ts,
);

export const PAYMENT_STATUSES = ['pending', 'approved', 'rejected'] as const;

/** Manual UPI payment: the firm pays by QR and submits the UTR + screenshot; the super admin approves. */
const PaymentRequestSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true, index: true },
    userId: { type: ObjectId, required: true },
    userEmail: String,
    /** "package" buys/renews a plan; "addon" adds capacity to the current license. */
    kind: { type: String, enum: ['package', 'addon'], default: 'package' },
    packageId: ObjectId,
    packageName: String,
    /** Add-on quantities (returnsPerMonth in returns, i.e. blocks × 10). */
    addon: { companies: Number, users: Number, returnsPerMonth: Number },
    /** The license the add-on is for. */
    forLicenseId: ObjectId,
    amountInr: { type: Number, required: true },
    durationDays: Number,
    upiId: String,
    utr: { type: String, required: true, uppercase: true, trim: true },
    note: String,
    screenshot: { type: Buffer, select: false },
    screenshotType: String,
    screenshotSize: Number,
    status: { type: String, enum: PAYMENT_STATUSES, default: 'pending', index: true },
    reviewedAt: Date,
    reviewedBy: String,
    reviewNote: String,
    licenseId: ObjectId,
  },
  ts,
);
PaymentRequestSchema.index({ utr: 1 });

/* Audit (append-only, hash-chained per org) */

const AuditLogSchema = new Schema({
  orgId: { type: ObjectId, required: true },
  seq: { type: Number, required: true },
  at: { type: Date, required: true },
  actorId: ObjectId,
  actorEmail: String,
  action: { type: String, required: true },
  entity: String,
  entityId: String,
  meta: Mixed,
  prevHash: String,
  hash: { type: String, required: true },
}, { minimize: false });
AuditLogSchema.index({ orgId: 1, seq: 1 }, { unique: true });
AuditLogSchema.index({ orgId: 1, entityId: 1, at: -1 });
const immutable = function () {
  throw new Error('Audit log is append-only');
};
for (const op of ['updateOne', 'updateMany', 'findOneAndUpdate', 'replaceOne', 'deleteOne', 'deleteMany', 'findOneAndDelete', 'findOneAndReplace'] as const) {
  AuditLogSchema.pre(op, immutable);
}

export const Organization = model('Organization', OrganizationSchema);
export const User = model('User', UserSchema);
export const Company = model('Company', CompanySchema);
export const GstReturn = model('GstReturn', GstReturnSchema);
export const Gstr1Record = model('Gstr1Record', Gstr1RecordSchema);
export const Gstr1Error = model('Gstr1Error', Gstr1ErrorSchema);
export const GeneratedJson = model('GeneratedJson', GeneratedJsonSchema);
export const UploadJob = model('UploadJob', UploadJobSchema);
export const PortalEvidence = model('PortalEvidence', PortalEvidenceSchema);
export const GstApiSession = model('GstApiSession', GstApiSessionSchema);
export const GstSession = model('GstSession', GstSessionSchema);
export const GstProfile = model('GstProfile', GstProfileSchema);
export const Gstr3b = model('Gstr3b', Gstr3bSchema);
export const AnnualReturn = model('AnnualReturn', AnnualReturnSchema);
export const ClientDoc = model('ClientDoc', ClientDocSchema);
export const PortalFetch = model('PortalFetch', PortalFetchSchema);
export const DocRecord = model('DocRecord', DocRecordSchema);
export const AssistantChat = model('AssistantChat', AssistantChatSchema);
export const AiUsage = model('AiUsage', AiUsageSchema);
export const PurchaseDoc = model('PurchaseDoc', PurchaseDocSchema);
export const PurchaseImport = model('PurchaseImport', PurchaseImportSchema);
export const ReconDecision = model('ReconDecision', ReconDecisionSchema);
export const SuperAdmin = model('SuperAdmin', SuperAdminSchema);
export const Package = model('Package', PackageSchema);
export const License = model('License', LicenseSchema);
export const PlatformSettings = model('PlatformSettings', PlatformSettingsSchema);
export const PaymentRequest = model('PaymentRequest', PaymentRequestSchema);
export const AuditLog = model('AuditLog', AuditLogSchema);

export type CompanyDoc = InferSchemaType<typeof CompanySchema> & { _id: Types.ObjectId };
export type GstReturnDoc = InferSchemaType<typeof GstReturnSchema> & { _id: Types.ObjectId };
export type Gstr3bDoc = InferSchemaType<typeof Gstr3bSchema> & { _id: Types.ObjectId };
export type ClientDocDoc = InferSchemaType<typeof ClientDocSchema> & { _id: Types.ObjectId };
export type DocRecordDoc = InferSchemaType<typeof DocRecordSchema> & { _id: Types.ObjectId };
export type AnnualReturnDoc = InferSchemaType<typeof AnnualReturnSchema> & { _id: Types.ObjectId };
export const oid = (s: string) => (Types.ObjectId.isValid(s) ? new Types.ObjectId(s) : null);
