import 'server-only';
import mongoose, { Schema, type InferSchemaType, type Model, Types } from 'mongoose';

const { Mixed, ObjectId } = Schema.Types;
const ts = { timestamps: true } as const;

function model<T>(name: string, schema: Schema<T>): Model<T> {
  return (mongoose.models[name] as Model<T>) ?? mongoose.model<T>(name, schema);
}

/* Tenancy & access */

const OrganizationSchema = new Schema(
  {
    name: { type: String, required: true },
    /** The license currently in force (see src/server/license.ts). */
    licenseId: { type: ObjectId },
  },
  ts,
);

export const ROLES = ['owner', 'admin', 'preparer', 'reviewer', 'viewer'] as const;
export type Role = (typeof ROLES)[number];

const UserSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true, index: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    name: { type: String, required: true },
    passwordHash: { type: String, required: true, select: false },
    role: { type: String, enum: ROLES, required: true },
    /** Empty = all companies in the org. */
    companyIds: [{ type: ObjectId }],
    active: { type: Boolean, default: true },
  },
  ts,
);

const CompanySchema = new Schema(
  {
    orgId: { type: ObjectId, required: true, index: true },
    name: { type: String, required: true },
    gstin: { type: String, required: true, uppercase: true },
    stateCode: { type: String, required: true },
    aatoAbove5Cr: { type: Boolean, default: false },
    filingFrequency: { type: String, enum: ['monthly', 'quarterly'], default: 'monthly' },
  },
  ts,
);
CompanySchema.index({ orgId: 1, gstin: 1 }, { unique: true });

/* Returns */

import { RETURN_STATUSES } from './gst/gst-status/statuses';
export { RETURN_STATUSES };

const GstReturnSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    fp: { type: String, required: true }, // MMYYYY
    fy: { type: String, required: true },
    quarterly: { type: Boolean, default: false },
    status: { type: String, enum: RETURN_STATUSES, default: 'draft' },
    statusHistory: [
      {
        _id: false, from: String, to: String, at: Date, by: ObjectId, byEmail: String, note: String, evidenceId: ObjectId,
      },
    ],
    /** References copied from portal evidence the user supplied – never generated by the app. */
    portal: {
      uploadReference: String,
      processingReference: String,
      arn: String,
      filedOn: Date,
      /** API integration only – values returned by GSTN through the client named in filedVia. */
      proceedReference: String,
      proceededAt: Date,
      summaryEvidenceId: ObjectId,
      evcRequestedAt: Date,
      fileSubmittedAt: Date,
      ackNum: String,
      filedVia: String,
    },
    profileId: String,
    importInfo: {
      fileName: String,
      importedAt: Date,
      sheetsParsed: Mixed,
      sheetsSkipped: Mixed,
      importIssueCount: Number,
    },
    summary: Mixed,
    lastValidatedAt: Date,
    currentJsonId: { type: ObjectId },
    jsonStale: { type: Boolean, default: false },
  },
  ts,
);
GstReturnSchema.index({ orgId: 1, companyId: 1, fp: 1 }, { unique: true });

const Gstr1RecordSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true },
    section: { type: String, required: true },
    key: { type: String, required: true },
    source: Mixed,
    data: { type: Mixed, required: true },
    hasErrors: { type: Boolean, default: false },
    hasWarnings: { type: Boolean, default: false },
    edited: { type: Boolean, default: false },
  },
  { ...ts, minimize: false },
);
Gstr1RecordSchema.index({ returnId: 1, section: 1, hasErrors: -1 });

const Gstr1ErrorSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true },
    origin: { type: String, enum: ['import', 'validation', 'portal'], required: true },
    recordKey: String,
    code: String,
    severity: { type: String, enum: ['error', 'warning'] },
    section: String,
    documentNo: String,
    sheet: String,
    row: Number,
    field: String,
    value: Mixed,
    message: String,
    suggestion: String,
  },
  ts,
);
Gstr1ErrorSchema.index({ returnId: 1, origin: 1, severity: 1 });

const GeneratedJsonSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true, index: true },
    version: String,
    profileId: String,
    /** Stored as the exact string that is downloaded/uploaded so the hash stays verifiable. */
    payload: { type: String, required: true },
    sha256: { type: String, required: true },
    sizeBytes: Number,
    log: Mixed,
    createdBy: ObjectId,
  },
  ts,
);

/* GST portal step (manual today; official integration later) */

const UploadJobSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true, index: true },
    jsonId: { type: ObjectId, required: true },
    jsonSha256: String,
    /** Which GstClient handled it – "manual" means the user uploads on the GST portal. */
    client: { type: String, required: true },
    status: { type: String, enum: ['uploading', 'uploaded', 'processing', 'processed', 'error', 'cancelled', 'filed'], default: 'uploading' },
    reference: String,
    portalErrorCount: Number,
    history: [{ _id: false, at: Date, status: String, note: String, by: String }],
    createdBy: ObjectId,
  },
  ts,
);

export const EVIDENCE_KINDS = ['upload_reference', 'error_report', 'processing_result', 'summary', 'acknowledgement', 'note'] as const;

/** Anything the user brings back from the GST portal: references, reports, acknowledgements. */
const PortalEvidenceSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    returnId: { type: ObjectId, required: true, index: true },
    uploadJobId: ObjectId,
    kind: { type: String, enum: EVIDENCE_KINDS, required: true },
    reference: String,
    note: String,
    fileName: String,
    contentType: String,
    sizeBytes: Number,
    sha256: String,
    content: { type: Buffer, select: false },
    recordedBy: ObjectId,
    recordedByEmail: String,
  },
  ts,
);

/**
 * Taxpayer session with GSTN through an API integration (one per company). The access token and the
 * GST username are AES-256-GCM encrypted, bound to org/company/GSTIN, and never leave the server.
 */
const GstApiSessionSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    client: { type: String, required: true },
    state: { type: String, enum: ['otp_sent', 'active', 'expired', 'none'], default: 'none' },
    usernameEnc: { type: String, select: false },
    tokenEnc: { type: String, select: false },
    otpSentAt: Date,
    sessionExpiresAt: Date,
    tokenExpiresAt: Date,
    lastRefreshAt: Date,
    startedBy: ObjectId,
    startedByEmail: String,
  },
  ts,
);
GstApiSessionSchema.index({ orgId: 1, companyId: 1 }, { unique: true });

/** GST portal (browser-protocol) session per company. The cookie jar is encrypted and never leaves the server. */
const GstSessionSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    gstin: { type: String, required: true },
    state: { type: String, enum: ['captcha_required', 'otp_required', 'active', 'failed', 'expired', 'none'], default: 'none' },
    jarEnc: { type: String, select: false },
    expiresAt: Date,
    lastActivityAt: Date,
    message: String,
    startedBy: ObjectId,
  },
  ts,
);
GstSessionSchema.index({ orgId: 1, companyId: 1 }, { unique: true });

/** Saved (encrypted) GST portal username per company, when the user opts to remember it. */
const GstProfileSchema = new Schema(
  {
    orgId: { type: ObjectId, required: true },
    companyId: { type: ObjectId, required: true },
    usernameEnc: String,
  },
  ts,
);
GstProfileSchema.index({ orgId: 1, companyId: 1 }, { unique: true });

/* Platform: super admin, packages and licenses (not scoped to an org) */

/** Software owner. Separate from org users; signs in at /admin. */
const SuperAdminSchema = new Schema(
  {
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    name: { type: String, default: 'Super Admin' },
    passwordHash: { type: String, required: true, select: false },
    active: { type: Boolean, default: true },
    lastLoginAt: Date,
  },
  ts,
);

export const FEATURE_KEYS = ['validators', 'gstApi'] as const;
export type FeatureKey = (typeof FEATURE_KEYS)[number];

/** A sellable plan. 0 in a limit means unlimited. */
const PackageSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    description: String,
    priceInr: { type: Number, default: 0 },
    durationDays: { type: Number, required: true },
    limits: {
      companies: { type: Number, default: 0 },
      users: { type: Number, default: 0 },
      returnsPerMonth: { type: Number, default: 0 },
    },
    features: [{ type: String, enum: FEATURE_KEYS }],
    /** Given automatically to new sign-ups. */
    isTrial: { type: Boolean, default: false },
    /** Archived packages keep working for existing licenses but cannot be issued. */
    active: { type: Boolean, default: true },
  },
  ts,
);

export const LICENSE_STATUSES = ['unused', 'active', 'suspended', 'revoked', 'replaced'] as const;

const LicenseSchema = new Schema(
  {
    key: { type: String, required: true, unique: true },
    packageId: { type: ObjectId, required: true, index: true },
    durationDays: { type: Number, required: true },
    status: { type: String, enum: LICENSE_STATUSES, default: 'unused' },
    orgId: { type: ObjectId, index: true },
    activatedAt: Date,
    expiresAt: Date,
    /** Customer name / reference, for the super admin's records. */
    issuedTo: String,
    note: String,
    createdBy: ObjectId,
  },
  ts,
);

/* Audit (append-only, hash-chained per org) */

const AuditLogSchema = new Schema({
  orgId: { type: ObjectId, required: true },
  seq: { type: Number, required: true },
  at: { type: Date, required: true },
  actorId: ObjectId,
  actorEmail: String,
  action: { type: String, required: true },
  entity: String,
  entityId: String,
  meta: Mixed,
  prevHash: String,
  hash: { type: String, required: true },
}, { minimize: false });
AuditLogSchema.index({ orgId: 1, seq: 1 }, { unique: true });
AuditLogSchema.index({ orgId: 1, entityId: 1, at: -1 });
const immutable = function () {
  throw new Error('Audit log is append-only');
};
for (const op of ['updateOne', 'updateMany', 'findOneAndUpdate', 'replaceOne', 'deleteOne', 'deleteMany', 'findOneAndDelete', 'findOneAndReplace'] as const) {
  AuditLogSchema.pre(op, immutable);
}

export const Organization = model('Organization', OrganizationSchema);
export const User = model('User', UserSchema);
export const Company = model('Company', CompanySchema);
export const GstReturn = model('GstReturn', GstReturnSchema);
export const Gstr1Record = model('Gstr1Record', Gstr1RecordSchema);
export const Gstr1Error = model('Gstr1Error', Gstr1ErrorSchema);
export const GeneratedJson = model('GeneratedJson', GeneratedJsonSchema);
export const UploadJob = model('UploadJob', UploadJobSchema);
export const PortalEvidence = model('PortalEvidence', PortalEvidenceSchema);
export const GstApiSession = model('GstApiSession', GstApiSessionSchema);
export const GstSession = model('GstSession', GstSessionSchema);
export const GstProfile = model('GstProfile', GstProfileSchema);
export const SuperAdmin = model('SuperAdmin', SuperAdminSchema);
export const Package = model('Package', PackageSchema);
export const License = model('License', LicenseSchema);
export const AuditLog = model('AuditLog', AuditLogSchema);

export type CompanyDoc = InferSchemaType<typeof CompanySchema> & { _id: Types.ObjectId };
export type GstReturnDoc = InferSchemaType<typeof GstReturnSchema> & { _id: Types.ObjectId };
export const oid = (s: string) => (Types.ObjectId.isValid(s) ? new Types.ObjectId(s) : null);
