import { describe, expect, it } from 'vitest';
import { buildSampleWorkbook, R_KA, R_MH, SUPPLIER } from '../../scripts/sample-workbook';
import {
  checkGstr1Json, checkHsn, describeGstin, fixGstr1Json, generateGstr1Json, markAutoFixable, parseGstr1Tables, profileForPeriod, readWorkbook,
  type ReturnContext,
} from './index';

const ctx = (): ReturnContext => ({ supplierGstin: SUPPLIER, fp: '062025', aatoAbove5Cr: false, profile: profileForPeriod('062025') });
const today = new Date(Date.UTC(2025, 7, 1));

async function cleanJson() {
  const tables = await readWorkbook(await buildSampleWorkbook(false));
  const { records } = parseGstr1Tables(tables, { supplierGstin: SUPPLIER, hsnSplit: true });
  return generateGstr1Json(records, ctx()).json as Record<string, unknown>;
}

describe('HSN check', () => {
  it('accepts valid goods and service codes with descriptions', () => {
    expect(checkHsn('8471')).toMatchObject({ ok: true, kind: 'goods', chapterName: expect.stringContaining('Machinery') });
    expect(checkHsn('998314')).toMatchObject({ ok: true, kind: 'service', heading: '9983' });
    expect(checkHsn('8471.30 10').code).toBe('84713010');
  });
  it('rejects bad shape, chapters and SAC headings', () => {
    expect(checkHsn('84713').ok).toBe(false);
    expect(checkHsn('7701').ok).toBe(false);
    expect(checkHsn('0012').ok).toBe(false);
    expect(checkHsn('9950').ok).toBe(false);
    expect(checkHsn('84A1').ok).toBe(false);
  });
  it('applies the turnover band', () => {
    expect(checkHsn('8471', { aatoAbove5Cr: true }).ok).toBe(false);
    expect(checkHsn('8471', { aatoAbove5Cr: true, b2b: false }).ok).toBe(true);
    expect(checkHsn('847130', { aatoAbove5Cr: true }).ok).toBe(true);
  });
});

describe('GSTIN breakdown', () => {
  it('explains a valid GSTIN', () => {
    const d = describeGstin('33ABKCS2033B1ZW');
    expect(d).toMatchObject({ ok: true, stateName: 'Tamil Nadu', pan: 'ABKCS2033B', panHolder: 'Company', entityNo: '1', registrationType: 'Normal taxpayer' });
  });
  it('reports the reason for an invalid one', () => {
    expect(describeGstin('27AAACR5055K1ZX')).toMatchObject({ ok: false, reason: expect.stringContaining('check digit') });
  });
});

describe('JSON validator', () => {
  it('passes JSON generated by the app', async () => {
    const r = checkGstr1Json(JSON.stringify(await cleanJson()), { aatoAbove5Cr: false, today });
    expect(r.issues.filter((i) => i.severity === 'error')).toEqual([]);
    expect(r.ok).toBe(true);
    expect(r.sections.b2b.documents).toBe(5);
    expect(r.stages.map((s) => s.status)).not.toContain('fail');
  });

  it('reports syntax errors with a position', () => {
    const r = checkGstr1Json('{\n  "gstin": "x",\n  "fp" "062025"\n}', { aatoAbove5Cr: false });
    expect(r.ok).toBe(false);
    expect(r.issues[0]).toMatchObject({ stage: 'parse', code: 'JSON_SYNTAX' });
    expect(r.stages.find((s) => s.id === 'rules')?.status).toBe('skipped');
  });

  it('finds header, schema, rule and JSON-only problems with paths', async () => {
    const j = await cleanJson();
    const b2b = j.b2b as { ctin: string; inv: { inum: string; itms: { itm_det: Record<string, number> }[] }[] }[];
    const ka = b2b.find((x) => x.ctin === R_KA)!;
    ka.inv[0].itms[0].itm_det.rt = 13;                        // invalid rate (rule)
    ka.inv[0].itms[1].itm_det.rt = 13;                        // same rate twice (json-only)
    (j.b2cs as Record<string, unknown>[])[0].sply_ty = 'XX';  // enum (schema)
    j.extra = 1;                                              // unknown field (schema warning)
    j.version = 'GST3.0.0';                                   // version (header warning)
    (j.doc_issue as { doc_det: { docs: Record<string, number>[] }[] }).doc_det[0].docs[0].net_issue = 99;
    const r = checkGstr1Json(j, { aatoAbove5Cr: false, today });
    const find = (code: string) => r.issues.find((i) => i.code === code);
    expect(r.ok).toBe(false);
    expect(find('JSON_VERSION')?.severity).toBe('warning');
    expect(find('SCHEMA_UNKNOWN_FIELD')).toMatchObject({ severity: 'warning', path: 'extra' });
    // reported once – by the more specific rule – rather than by both the schema and the rule
    expect(r.issues.filter((i) => i.path === 'b2cs[0].sply_ty').map((i) => i.code)).toEqual(['JSON_SPLY_TY']);
    expect(find('JSON_RATE_REPEATED')).toBeTruthy();
    expect(find('JSON_NET_ISSUE')?.path).toBe('doc_issue.doc_det[0].docs[0].net_issue');
    const rate = r.issues.find((i) => i.stage === 'rules' && i.message.includes('not a valid GST rate'));
    expect(rate?.path).toMatch(/^b2b\[\d+\]\.inv\[0\]\.itms\[0\]\.itm_det\.rt$/);
  });

  it('flags the wrong HSN layout for the period and a future period', async () => {
    const j = await cleanJson();
    j.hsn = { data: [...((j.hsn as Record<string, unknown[]>).hsn_b2b), ...((j.hsn as Record<string, unknown[]>).hsn_b2c)] };
    const r = checkGstr1Json(j, { aatoAbove5Cr: false, today });
    expect(r.issues.some((i) => i.code === 'JSON_HSN_FORMAT')).toBe(true);
    const future = checkGstr1Json({ ...j, fp: '122030' }, { aatoAbove5Cr: false, today });
    expect(future.issues.some((i) => i.code === 'JSON_FP_FUTURE')).toBe(true);
  });
});

describe('JSON auto-fix', () => {
  it('leaves an app-generated JSON unchanged', async () => {
    const j = await cleanJson();
    const { json, fixes } = fixGstr1Json(j);
    expect(fixes).toEqual([]);
    expect(json).toEqual(j);
  });

  it('repairs the deterministic problems and the result validates clean', async () => {
    const j = await cleanJson();
    const b2b = j.b2b as { ctin: string; inv: Record<string, unknown>[] }[];
    const inv = b2b[0].inv[0] as { itms: { num: number; itm_det: Record<string, unknown> }[]; pos: unknown; idt: unknown };
    const det = inv.itms[0].itm_det;
    det.txval = String(det.txval);                                     // number stored as text
    if ('iamt' in det) { det.camt = det.iamt; delete det.iamt; }       // wrong tax head
    else { det.iamt = 999; delete det.camt; delete det.samt; }
    inv.idt = '2025-06-10';                                            // ISO date
    b2b.push({ ctin: b2b[0].ctin, inv: [] });                          // repeated group
    (j.b2cs as Record<string, unknown>[])[0].sply_ty = 'INTER';        // wrong sply_ty (intra POS in sample)
    (j.doc_issue as { doc_det: { docs: Record<string, number>[] }[] }).doc_det[0].docs[0].net_issue = 99;
    j.version = 'GST1.0';
    j.extra = true;
    const before = checkGstr1Json(j, { aatoAbove5Cr: false, today });
    expect(before.ok).toBe(false);

    const { json, fixes } = fixGstr1Json(j);
    const codes = new Set(fixes.map((f) => f.code));
    for (const c of ['FORMAT', 'TAX_RECALCULATED', 'GROUP_MERGED', 'NET_ISSUE', 'VERSION', 'UNKNOWN_FIELD']) expect(codes).toContain(c);
    const after = checkGstr1Json(json, { aatoAbove5Cr: false, today });
    expect(after.issues.filter((i) => i.severity === 'error')).toEqual([]);
    expect((json as Record<string, unknown>).extra).toBeUndefined();
    expect(fixes.find((f) => f.code === 'NET_ISSUE')).toMatchObject({ path: 'doc_issue.doc_det[0].docs[0].net_issue', before: 99 });
  });

  it('merges same-rate items and does not touch what needs a person', async () => {
    const j = await cleanJson();
    const inv = (j.b2b as { inv: { inum: string; itms: { num: number; itm_det: Record<string, number> }[] }[] }[])[0].inv[0];
    inv.itms.push(structuredClone(inv.itms[0]));
    const tx = inv.itms[0].itm_det.txval;
    inv.inum = 'BAD NO#';
    const { json, fixes } = fixGstr1Json(j);
    const fixed = (json as typeof j & { b2b: typeof j.b2b }).b2b as typeof j.b2b & { inv: typeof inv[] }[];
    expect(fixes.some((f) => f.code === 'RATE_MERGED')).toBe(true);
    expect(fixed[0].inv[0].itms).toHaveLength(inv.itms.length - 1);
    expect(fixed[0].inv[0].itms[0].itm_det.txval).toBe(tx * 2);
    expect(fixed[0].inv[0].inum).toBe('BAD NO#');
  });
});

describe('markAutoFixable', () => {
  it('tags the findings the fixer would change, and not the ones needing a person', async () => {
    const j = await cleanJson();
    (j.doc_issue as { doc_det: { docs: Record<string, number>[] }[] }).doc_det[0].docs[0].net_issue = 99;
    const hsn = (j.hsn as { hsn_b2b: Record<string, unknown>[] }).hsn_b2b;
    hsn[0].hsn_sc = '778877';
    const r = markAutoFixable(checkGstr1Json(j, { aatoAbove5Cr: false, today }), j);
    expect(r.issues.find((i) => i.code === 'JSON_NET_ISSUE')?.autoFix).toBe(true);
    expect(r.issues.find((i) => i.path === 'hsn.hsn_b2b[0].hsn_sc')?.autoFix).toBeUndefined();
    expect(r.autoFixable).toBe(1);
    const clean = markAutoFixable(checkGstr1Json(await cleanJson(), { aatoAbove5Cr: false, today }), await cleanJson());
    expect(clean.autoFixable).toBe(0);
  });
});

describe('auto-fix on an offline-tool style file', () => {
  // Same pattern as a real offline-tool export: IGST understated on one invoice, freight HSN row with zero tax,
  // plus the gt / cur_gt / user_desc fields the offline tool writes.
  const file = () => ({
    gstin: SUPPLIER, fp: '062025', gt: 0, cur_gt: 0, version: 'GST3.2.2', hash: 'hash',
    b2b: [{ ctin: R_MH, inv: [
      { inum: 'A/1', idt: '05-06-2025', val: 11800, pos: '27', rchrg: 'N', inv_typ: 'R', itms: [{ num: 1801, itm_det: { txval: 10000, rt: 18, iamt: 1800, csamt: 0 } }] },
      { inum: 'A/2', idt: '06-06-2025', val: 590, pos: '27', rchrg: 'N', inv_typ: 'R', itms: [{ num: 1801, itm_det: { txval: 500, rt: 18, iamt: 0, csamt: 0 } }] },
    ] }],
    hsn: { hsn_b2b: [
      { num: 1, hsn_sc: '8471', user_desc: '', desc: '', uqc: 'NOS', qty: 5, rt: 18, txval: 10000, iamt: 1800, camt: 0, samt: 0, csamt: 0 },
      { num: 3, hsn_sc: '9965', user_desc: '', desc: '', uqc: 'NA', qty: 0, rt: 18, txval: 500, iamt: 0, camt: 0, samt: 0, csamt: 0 },
    ] },
    doc_issue: { doc_det: [{ doc_num: 1, doc_typ: 'Invoices for outward supply', docs: [{ num: 1, from: 'A/1', to: 'A/2', totnum: 2, cancel: 0, net_issue: 2 }] }] },
  });

  it('fixes invoice and HSN tax in one pass, keeps offline-tool fields and numbering', () => {
    const before = checkGstr1Json(file(), { aatoAbove5Cr: false, today });
    expect(before.issues.some((i) => i.code === 'SCHEMA_UNKNOWN_FIELD')).toBe(false);
    expect(before.issues.filter((i) => i.severity === 'error').length).toBe(2);

    const { json, fixes } = fixGstr1Json(file());
    const j = json as ReturnType<typeof file>;
    expect(fixes.map((f) => f.code).sort()).toEqual(['HSN_TAX', 'TAX_RECALCULATED']);
    expect(j.b2b[0].inv[1].itms[0].itm_det.iamt).toBe(90);
    expect(j.hsn.hsn_b2b[1]).toMatchObject({ iamt: 90, camt: 0, samt: 0, num: 3, user_desc: '' });
    expect(j.gt).toBe(0);
    expect(checkGstr1Json(json, { aatoAbove5Cr: false, today }).ok).toBe(true);
    expect(fixGstr1Json(json).fixes).toEqual([]); // nothing left to do on a second click
  });

  it('leaves HSN tax alone when the documents do not account for it', () => {
    const f = file();
    f.b2b[0].inv.pop(); // no invoice carries the freight tax any more
    const { fixes } = fixGstr1Json(f);
    expect(fixes.some((x) => x.code === 'HSN_TAX')).toBe(false);
  });
});

describe('HSN with spaces or dots', () => {
  const withHsn = async (code: string) => {
    const j = await cleanJson();
    const rows = (j.hsn as { hsn_b2b: Record<string, unknown>[] }).hsn_b2b;
    rows[0].hsn_sc = code;
    rows[0].iamt = 0; rows[0].camt = 0; rows[0].samt = 0; // the row's tax is also wrong, as on the reported screen
    return j;
  };

  it('reports it once, in plain words, and auto-fix cleans it', async () => {
    const j = await withHsn('8471.00');
    const r = markAutoFixable(checkGstr1Json(j, { aatoAbove5Cr: false, today }), j);
    const hsn = r.issues.filter((i) => i.path === 'hsn.hsn_b2b[0].hsn_sc');
    expect(hsn).toHaveLength(1);
    expect(hsn[0]).toMatchObject({ stage: 'rules', message: expect.stringContaining('digits only'), suggestion: 'Use 847100.', autoFix: true });
    expect(r.issues.some((i) => /must match pattern/.test(i.message))).toBe(false);
    const fixed = fixGstr1Json(j).json as typeof j;
    expect((fixed.hsn as { hsn_b2b: Record<string, unknown>[] }).hsn_b2b[0].hsn_sc).toBe('847100');
  });

  it('does not tag a code it cannot fix, even when it fixes other fields of the same row', async () => {
    const j = await withHsn('84A1');
    const r = markAutoFixable(checkGstr1Json(j, { aatoAbove5Cr: false, today }), j);
    const hsn = r.issues.find((i) => i.path === 'hsn.hsn_b2b[0].hsn_sc');
    expect(hsn?.autoFix).toBeUndefined();
    expect(hsn?.message).toMatch(/digits only/);
  });

  it('explains schema errors in plain words', async () => {
    const j = await cleanJson();
    const inv = (j.b2b as { inv: Record<string, unknown>[] }[])[0].inv[0];
    inv.rchrg = 'X';
    const r = checkGstr1Json(j, { aatoAbove5Cr: false, today });
    const rc = r.issues.find((i) => i.stage === 'schema' && i.path.endsWith('.rchrg'));
    expect(rc).toMatchObject({ message: 'Reverse charge must be one of: Y, N', value: 'X' });
  });
});
